config/routes.rb
Grosh::Application.routes.draw do
  match 'import' => 'items#import'

  resources :receipts

  resources :items

  root :to => 'receipts#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :receipt
  validates_presence_of :receipt_id
end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
  validates_presence_of :date

  has_many :items, :dependent => :destroy

  def total
    items.inject(0) {|sum, n| sum + n.total}
  end

  def pretty_total
    ActionController::Base.helpers.number_to_currency(total)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
require 'csv'

class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])
    @receipt = @item.receipt

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
        format.js { render layout: false, content_type: 'text/html' }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @receipt = @item.receipt
    @item.destroy

    respond_to do |format|
      format.html { redirect_to @receipt }
      format.json { head :no_content }
    end
  end

  def import
    if request.post?
      tmp = params[:file_upload][:my_file].tempfile

      @receipt = nil
      date = nil
      store = nil

      CSV.foreach(tmp.path, :headers => true) do |row|
        attrs = row.to_hash

        next if attrs['store'] == 'Total'

        # Rails.logger.debug "attrs: #{attrs}"

        if attrs['store']
          store = attrs['store']
          Rails.logger.debug "store: #{store}"
        end

        if attrs['date']
          date = Date.strptime(attrs['date'], '%m/%d/%y')
          Rails.logger.debug "create receipt: #{store} #{date}"
          @receipt = Receipt.create! :store => store, :date => date
        end

        attrs.delete 'store'
        attrs.delete 'date'

        count = attrs.delete('count').to_i
        count = 1 if count < 1

        count.times do
          Rails.logger.debug "adding item: #{attrs.inspect}"
          @receipt.items << Item.new(attrs)
        end
      end

      redirect_to :receipts
    end
  end

end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  # GET /receipts
  # GET /receipts.json
  def index
    @receipts = Receipt.find(:all,:order => :date)
    @total = @receipts.reduce(0) {|sum, r| sum + r.total }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @receipts }
    end
  end

  # GET /receipts/1
  # GET /receipts/1.json
  def show
    @receipt = Receipt.find(params[:id])
    @items = @receipt.items
    @categories = ['misc', 'beverages', 'carbs', 'condiments', 'household', 'produce', 'protein']

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @receipt }
    end
  end

  # GET /receipts/new
  # GET /receipts/new.json
  def new
    @receipt = Receipt.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @receipt }
    end
  end

  # GET /receipts/1/edit
  def edit
    @receipt = Receipt.find(params[:id])
  end

  # POST /receipts
  # POST /receipts.json
  def create
    @receipt = Receipt.new(params[:receipt])

    respond_to do |format|
      if @receipt.save
        format.html { redirect_to @receipt, notice: 'Receipt was successfully created.' }
        format.json { render json: @receipt, status: :created, location: @receipt }
      else
        format.html { render action: "new" }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /receipts/1
  # PUT /receipts/1.json
  def update
    @receipt = Receipt.find(params[:id])

    respond_to do |format|
      if @receipt.update_attributes(params[:receipt])
        format.html { redirect_to @receipt, notice: 'Receipt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts/1
  # DELETE /receipts/1.json
  def destroy
    @receipt = Receipt.find(params[:id])
    @receipt.destroy

    respond_to do |format|
      format.html { redirect_to receipts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :receipt %><br />
    <%= f.text_field :receipt_id %>
  </div>
  <div class="field">
    <%= f.label :store %><br />
    <%= f.text_field :store %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :units %><br />
    <%= f.text_field :units %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :price_per %><br />
    <%= f.text_field :price_per %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :total %><br />
    <%= f.text_field :total %>
  </div>
  <div class="field">
    <%= f.label :tax_code %><br />
    <%= f.text_field :tax_code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/create.html.erb
<%= render :partial => 'shared/item', :locals => {:item => @item, :receipt => @receipt } %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>All Items</h1>

<hr>

<%= render :partial => 'shared/list' %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Store:</b>
  <%= @item.store %>
</p>

<p>
  <b>Date:</b>
  <%= @item.date %>
</p>

<p>
  <b>Code:</b>
  <%= @item.code %>
</p>

<p>
  <b>Quantity:</b>
  <%= @item.quantity %>
</p>

<p>
  <b>Quantity per:</b>
  <%= @item.units %>
</p>

<p>
  <b>Price:</b>
  <%= @item.price %>
</p>

<p>
  <b>Price per:</b>
  <%= @item.price_per %>
</p>

<p>
  <b>Description:</b>
  <%= @item.description %>
</p>

<p>
  <b>Total:</b>
  <%= @item.total %>
</p>

<p>
  <b>Tax code:</b>
  <%= @item.tax_code %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Grosh" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Grosh</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Receipts", "/receipts"  %></li>
              <li><%= link_to "Items", "/items"  %></li>
              <li><%= link_to "Import", "/import"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/receipts/_form.html.erb
<%= form_for @receipt, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :store, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :store, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :date, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :date, :class => 'datetime_select' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                receipts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/receipts/edit.html.erb
<%- model_class = Receipt -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/receipts/index.html.erb
<%- model_class = Receipt -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_receipt_path,
            :class => 'btn btn-primary' %>


<div class="pull-right">total spent to date: <%= number_to_currency @total %></div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:store) %></th>
      <th>Date</th>
      <th>Items</th>
      <th>Total</th>
      <th>Created</th>
    </tr>
  </thead>
  <tbody>
    <% @receipts.each do |receipt| %>
      <tr>
        <td><%= receipt.id %></td>
        <td><%= link_to receipt.store, receipt_path(receipt) %></td>
        <td><%= receipt.date.to_date %></td>
        <td><%= receipt.items.count %></td>
        <td><%= receipt.pretty_total %></td>
        <td><%= time_ago_in_words(receipt.created_at) %> ago</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/receipts/new.html.erb
<%- model_class = Receipt -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/receipts/show.html.erb
<%- model_class = Receipt -%>
  <h1><%= @receipt.store %></h1>
  <h2><%= @receipt.date.to_date %></h2>

<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
            receipt_path(@receipt),
            :method => :delete,
            :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
            :class => 'btn btn-mini btn-danger' %>

<hr>
<%= render :partial => 'shared/list', :local => {:items => @receipt.items } %>

app/views/shared/_item.html.erb
  <div class="row-fluid">
    <% unless receipt %>
      <div class="span1"><%= item.receipt && item.receipt.store %></div>
      <div class="span2"><%= item.receipt && item.receipt.date.to_date %></div>
    <% end %>
    <div class="span2"><%= item.description %></div>
    <div class="span1"><%= item.code %></div>
    <div class="span1" style="text-align:right"><%= item.quantity %></div>
    <div class="span1"><%= item.units %></div>
    <div class="span1"><%= number_to_currency item.total %></div>
    <div class="span1"><%= item.tax_code %></div>
    <div class="span1"><%= item.category %></div>
    <div class="span1">
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      item_path(item),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
    </div>
  </div>

app/views/shared/_list.html.erb
<div class="row-fluid">
  <% unless @receipt %>
    <div class="span1"><b>Store</b></div>
    <div class="span2"><b>Date</b></div>
  <% end %>
  <div class="span2"><b>Description</b></div>
  <div class="span1"><b>Code</b></div>
  <div class="span1"><b>Quantity</b></div>
  <div class="span1"><b>Units</b></div>
  <div class="span1"><b>Total</b></div>
  <div class="span1"><b>Tax Code</b></div>
  <div class="span1"><b>Category</b></div>
  <div class="span1"></div>
</div>

<div class="itemlist">
<% @items.each do |item| %>
  <%= render :partial => 'shared/item', :locals => { :item => item, :receipt => @receipt } %>
<% end %>
</div>

<% if @receipt %>
  <%= form_for(Item.new, :html => {:class => 'form-inline'}, :remote => true) do |f| %>
  <%= f.hidden_field :receipt_id, :value => @receipt.id, :class => 'span12' %>
  <div class="row-fluid">
    <div class="span2"><%= f.text_field :description, :class => 'span12', :placeholder => 'description' %></div>
    <div class="span1"><%= f.text_field :code, :class => 'span12', :placeholder => 'code' %></div>
    <div class="span1"><%= f.text_field :quantity, :class => 'span12', :placeholder => 'quantity' %></div>
    <div class="span1"><%= f.text_field :units, :class => 'span12', :placeholder => 'units' %></div>
    <div class="span1"><%= f.text_field :total, :class => 'span12', :placeholder => 'cost' %></div>
    <div class="span1"><%= f.text_field :tax_code, :class => 'span12', :placeholder => 'taxcode' %></div>
    <div class="span1">
      <%= f.select :category, @categories, {}, {:class => 'span12'} %>
    </div>
    <div class="span1"><%= f.submit :value => "add", :class => 'btn btn-primary' %></div>
  </div>
  <% end %>
  <div class="row-fluid">
    <div class="span2"><b>Sub total:</b></div>
    <div class="span3"></div>
    <div class="span1"><%= number_to_currency @receipt.total %></div>
  </div>
<% end %>